### ISSUE TITLE
No underscores in xake name

### ISSUE THREAD

**Issue by betahat** [XimeraProject/OLDxake#6]
If there are underscores in the name of the ximera repo (xake name ***), the page won't serve.

I'm not sure whether this is intentional, so either allowing it as a valid name or a note on the readme indicating the rules might be helpful.

**Comment by kisonecat** [comment]
We should indeed have some documentation on this -- and better warnings
about failures.

For now, only lowercase letters and digits are permitted.

**Comment by kisonecat** [comment]
The repository name normalization in https://github.com/XimeraProject/server/commit/9a15f47016ff73333c6dc8a63931d2b9c3126a78 should also help with this.
